# Generated by Django 5.2.12 on 2026-04-10 07:29

from urllib.parse import urlparse
from urllib.request import Request, urlopen

import django.core.validators
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage
from django.db import migrations, models


PLACEHOLDER_GIF = (
    b"GIF89a\x01\x00\x01\x00\x80\x00\x00\x00\x00\x00"
    b"\xff\xff\xff!\xf9\x04\x00\x00\x00\x00\x00,\x00\x00"
    b"\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;"
)


def _guess_extension(url):
    path = urlparse(url).path.lower()
    if path.endswith(".png"):
        return "png"
    if path.endswith(".gif"):
        return "gif"
    if path.endswith(".webp"):
        return "webp"
    if path.endswith(".jpeg"):
        return "jpeg"
    return "jpg"


def _download_or_placeholder(url):
    try:
        req = Request(url, headers={"User-Agent": "RoomieHKU-Migration/1.0"})
        with urlopen(req, timeout=10) as resp:  # nosec B310
            data = resp.read()
            if data:
                return data
    except Exception:
        pass
    return PLACEHOLDER_GIF


def _migrate_legacy_image_values(apps, schema_editor):
    User = apps.get_model("core", "User")
    Post = apps.get_model("core", "Post")

    for user in User.objects.exclude(profile_photo__isnull=True).exclude(profile_photo=""):
        value = str(user.profile_photo)
        if value.startswith(("http://", "https://")):
            ext = _guess_extension(value)
            file_name = f"profile_photos/legacy-user-{user.pk}.{ext}"
            if not default_storage.exists(file_name):
                default_storage.save(file_name, ContentFile(_download_or_placeholder(value)))
            user.profile_photo = file_name
            user.save(update_fields=["profile_photo"])

    for post in Post.objects.exclude(image_url=""):
        value = str(post.image_url)
        if value.startswith(("http://", "https://")):
            ext = _guess_extension(value)
            file_name = f"listing_images/legacy-post-{post.pk}.{ext}"
            if not default_storage.exists(file_name):
                default_storage.save(file_name, ContentFile(_download_or_placeholder(value)))
            post.image_url = file_name
            post.save(update_fields=["image_url"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.FileField(help_text='Upload listing image', upload_to='listing_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='profile_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
        migrations.RunPython(_migrate_legacy_image_values, migrations.RunPython.noop),
    ]
